name: Deployment Google Cloud

on:
  push:
    branches: ["main"]

jobs:
  environment:
    runs-on: ubuntu-20.04
    steps:
    # Actualización del código
      - name: Check-skip
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: pwd
      - run: ls
      - run: ls -1

  VM_google_cloud:
    runs-on: ubuntu-20.04
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      # Actualización del código
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Identificación en google cloud
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
     # Accedemos al sdk gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      # Listamos las VM que tenemos en google cloud
      - name: List VM
        run: gcloud compute instances list
      #Creamos la VM
      - name: Create VM
        run: gcloud compute instances create rick-and-morty-vm-${{ github.sha }} --machine-type=n1-standard-1 --zone=us-central1-a
      # Listamos las VM que tenemos en google cloud
      - name: List VM
        run: gcloud compute instances list
        #Creamos la regla de firewall para el ssh
      - name: create firewall-rules
        run: gcloud compute --project=primerproyecto-flask firewall-rules create rule-${{ github.sha }} --direction=INGRESS --priority=1000 --network=default --action=ALLOW --rules=tcp:80 --source-ranges=0.0.0.0/0 --target-tags=red-tag
      # Borramos las VM que tenemos en google cloud
      - name: Delete VM
        run: gcloud compute instances delete rick-and-morty-vm-${{ github.sha }} --zone=us-central1-a
      # Listamos las VM que tenemos en google cloud
      - name: List VM
        run: gcloud compute instances list




        