name: Instalación de sistema operativo ubuntu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize]

jobs:
  environment:
    runs-on: ubuntu-20.04
    steps:
      - name: Check-skip
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: pwd
      - run: ls
      - run: ls -1